# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_cat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QLabel(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 551, 551))
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 140, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 270, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 400, 91, 21))
        self.label_6.setObjectName("label_6")
        self.textEdit_weight = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_weight.setGeometry(QtCore.QRect(600, 300, 161, 41))
        self.textEdit_weight.setObjectName("textEdit_weight")
        self.textEdit_time = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_time.setGeometry(QtCore.QRect(600, 430, 161, 41))
        self.textEdit_time.setObjectName("textEdit_time")
        self.textEdit_location = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_location.setGeometry(QtCore.QRect(600, 170, 161, 41))
        self.textEdit_location.setObjectName("textEdit_location")
        self.textEdit_name = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_name.setGeometry(QtCore.QRect(600, 60, 161, 41))
        self.textEdit_name.setObjectName("textEdit_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "名称："))
        self.label_3.setText(_translate("MainWindow", "地点："))
        self.label_4.setText(_translate("MainWindow", "投喂量："))
        self.label_6.setText(_translate("MainWindow", "当前投喂时间："))
